version: "3"
services:
  dashdot:
    container_name: dashdot
    image: mauricenino/dashdot:latest
    ports:
      - 'x:3001'
    restart: unless-stopped
    privileged: true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
