version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.5
    restart: unless-stopped
    container_name: nextcloud_db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD={{ROOT_PASSWORD}}
      - MYSQL_PASSWORD={{PASSWORD}}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  app:
    image: nextcloud
    restart: unless-stopped
    container_name: nextcloud_app
    ports:
      - x:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      - /mnt/x:/mnt/nas/photos:rw
      - /mnt/x:/mnt/nas/notes:rw
    environment:
      - MYSQL_PASSWORD={{PASSWORD}}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
