---
version: "3.4"
services:
  vpn:
    container_name: protonvpn
    image: qmcgaw/gluetun:v3.29
    cap_add:
      - net_admin
    restart: unless-stopped
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /dev/net:/dev/net:z
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=
      - SERVER_COUNTRIES=United States
      - FIREWALL_VPN_INPUT_PORTS=
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deluge.entrypoints=http"
      - "traefik.http.routers.deluge.rule=Host(`deluge.local.willkimble.net`)"
      - "traefik.http.middlewares.deluge-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.deluge.middlewares=deluge-https-redirect"
      - "traefik.http.routers.deluge-secure.entrypoints=https"
      - "traefik.http.routers.deluge-secure.rule=Host(`deluge.local.willkimble.net`)"
      - "traefik.http.routers.deluge-secure.tls=true"
      - "traefik.http.routers.deluge-secure.service=deluge"
      - "traefik.http.services.deluge.loadbalancer.server.port=8112"
      - "traefik.docker.network=proxy"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.deluge-secure.middlewares=authelia@docker"

  deluge:
    container_name: deluge
    image: linuxserver/deluge:amd64-2.0.5-r1-ls162
    restart: unless-stopped
    network_mode: "service:vpn"
    depends_on:
      - vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:deluge
    volumes:
      - ./config:/config
      - /mnt/{NAS}/Downloads:/downloads
      - /mnt/{NAS}/Videos/Television:/tv
      - /mnt/{NAS}/Videos/Movies:/movie
      - /mnt/{NAS}/Videos/Masterclass:/masterclass
      - /mnt/{NAS}/Books/Calibre/Seeding:/books
      - /mnt/{NAS}/Books/Audiobooks:/audiobooks

networks:
  proxy:
    external: true
