---
version: "2.1"
services:
  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ./config:/config
      - /mnt/x:/downloads
      - /mnt/x:/tv
      - /mnt/x:/movie
      - /mnt/x:/books
      - /mnt/x:/audiobooks
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
