---
version: "3.4"
services:
  vpn:
    container_name: protonvpn
    image: qmcgaw/gluetun:v3.29
    cap_add:
      - net_admin
    restart: unless-stopped
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /dev/net:/dev/net:z
    security_opt:
      - label:disable
    ports:
      - {{PORT}}:8112
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER={{USER}}
      - OPENVPN_PASSWORD={{PASSWORD}}
      - SERVER_COUNTRIES=United States
      - FIREWALL_VPN_INPUT_PORTS={{PORT}}

  deluge:
    container_name: deluge
    image: linuxserver/deluge:amd64-2.0.5-r1-ls162
    restart: unless-stopped
    network_mode: "service:vpn"
    depends_on:
      - vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:deluge
    volumes:
      - ./config:/config
      - /Downloads:/downloads
      - /Television:/tv
      - /Movies:/movie
      - /Masterclass:/masterclass
      - /Calibre/Seeding:/books
      - /Audiobooks:/audiobooks

