---
version: "2"
services:
  shiori:
    image: radhifadlillah/shiori
    container_name: shiori
    volumes:
      - ./data:/data
    environment:
      - UID=1000
      - GID=1000
      - SHIORI_DIR=/data
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shiori.entrypoints=http"
      - "traefik.http.routers.shiori.rule=Host(`shiori.local.willkimble.net`)"
      - "traefik.http.middlewares.shiori-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.shiori.middlewares=shiori-https-redirect"
      - "traefik.http.routers.shiori-secure.entrypoints=https"
      - "traefik.http.routers.shiori-secure.rule=Host(`shiori.local.willkimble.net`)"
      - "traefik.http.routers.shiori-secure.tls=true"
      - "traefik.http.routers.shiori-secure.service=shiori"
      - "traefik.http.services.shiori.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.shiori-secure.middlewares=authelia@docker"

networks:
  proxy:
    external: true
