version: "3.1"
services:
  mealie:
    container_name: mealie
    image: hkotel/mealie:latest
    restart: unless-stopped
    ports:
      - 9925:80
    environment:
      TZ: America/Chicago
    volumes:
      - ./data/:/app/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
