---
title: "Homer"
subtitle: "No Bummers"
logo: "logo.png"

header: false
footer: false

stylesheet:
  - "assets/custom.css"

columns: "5" # You can change this to any number that is a factor of 12: (1, 2, 3, 4, 6, 12)
theme: default
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "#fff5f2"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/wallpaper-light.jpeg" # Change wallpaper.jpeg to the name of your own custom wallpaper!
  dark:
    highlight-primary: "#292929"
    highlight-secondary: "#292929"
    highlight-hover: "#1F2347"
    background: "#141414"
    card-background: "#1F1F1F"
    text: "#eaeaea"
    text-header: "#474747"
    text-title: "#fafafa"
    text-subtitle: "#666666"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/wallpaper.jpeg"

services:

  - name: "//Media Apps"
    icon: "fas fa-file"
    items:

      - name: "Nextcloud"
        logo: "assets/tools/nextcloud.png"
        subtitle: "Document Manager"
        tag: "documents"
        tagstyle: "is-dark"
        url: "{{URL}}"
        target: "_blank"

      - name: "Jellyfin"
        logo: "assets/tools/jellyfin.png"
        subtitle: "Media Manager"
        tag: "media"
        tagstyle: "is-dark"
        url: "{{URL}}"
        target: "_blank"

      - name: "Photoview"
        logo: "assets/tools/photoview.png"
        subtitle: "Photo Manager"
        tag: "photos"
        tagstyle: "is-dark"
        url: "{{URL}}"
        target: "_blank"

      - name: "Audiobookshelf"
        logo: "assets/tools/audiobookshelf.png"
        subtitle: "Book Manager"
        tag: "books"
        tagstyle: "is-dark"
        url: "{{URL}}"
        target: "_blank"


  - name: "//Home Apps"
    icon: "fas fa-home"
    items:


      - name: "Tandoor"
        logo: "assets/tools/tandoorrecipes.png"
        subtitle: "Recipe Manager"
        tag: "vegan"
        tagstyle: "is-dark"
        url: "{{URL}}"
        target: "_blank"

      - name: "Shiori"
        logo: "assets/tools/shiori.png"
        subtitle: "Articles Manager"
        tag: "bookmarks"
        tagstyle: "is-dark"
        url: "{{URL}}"
        target: "_blank"

      - name: "EmulatorJS"
        logo: "assets/tools/ejs.png"
        subtitle: "ROM Manager"
        tag: "games"
        tagstyle: "is-dark"
        url: "{{URL}}"
        target: "_blank"



  - name: "//Downloaders"
    icon: "fas fa-download"
    items:
      - name: "Deluge"
        logo: "assets/tools/deluge.png"
        subtitle: "Encrypted Client"
        tag: "vpn torrents"
        tagstyle: "is-danger"
        url: "{{URL}}"
        target: "_blank"

      - name: "qBittorrent"
        logo: "assets/tools/qbittorrent.png"
        subtitle: "Connectable Client"
        tag: "private torrents"
        tagstyle: "is-dark"
        url: "{{URL}}"
        target: "_blank"


  - name: "//Network"
    icon: "fas fa-network-wired"
    items:
      - name: "PiHole"
        logo: "assets/tools/pihole.png"
        subtitle: "DNS Sinkhole"
        tag: "dns"
        tagstyle: "is-dark"
        url: "{{URL}}"
        target: "_blank"

      - name: "Synology"
        logo: "assets/tools/synology.png"
        subtitle: "Personal NAS"
        tag: "nas"
        tagstyle: "is-dark"
        url: "{{URL}}"
        target: "_blank"

      - name: "AT&T Router"
        logo: "assets/tools/router.png"
        subtitle: "Wireless Router"
        tag: "router"
        tagstyle: "is-dark"
        url: "{{URL}}"
        target: "_blank"


  - name: "//Monitoring"
    icon: "fas fa-tachometer-alt"
    items:
      - name: "Uptime Kuma"
        logo: "assets/tools/uptime-kuma.png"
        subtitle: "Downtime Reporter"
        tag: "uptime"
        tagstyle: "is-dark"
        url: "{{URL}}"
        target: "_blank"

      - name: "Portainer"
        logo: "assets/tools/portainer.png"
        subtitle: "Docker Manager"
        tag: "docker"
        tagstyle: "is-dark"
        url: "{{URL}}"
        target: "_blank"
