---
version: "2.1"
services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./data:/data
      - ./config:/config
      - /mnt/synology-nas/Files/Videos/Television:/tv #optional
      - /mnt/synology-nas/Files/Downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
