---
version: "2.1"
services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./data:/data
      - ./config:/config
      - x:/tv #optional
      - x:/downloads #optional
    ports:
      - x:8989
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
