---
version: "0.1"
services:
  cartridge:
    image: jamjnsn/cartridge:latest
    container_name: cartridge
    ports:
      - x:80
    volumes:
      - ./data:/var/www/storage
      - /mnt/x:/games
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
