version: "3.4"
services:
  broker:
    container_name: paperless-ngx_broker
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/mariadb:10
    container_name: paperless-ngx_db
    restart: unless-stopped
    volumes:
      - ./data/dbdata:/var/lib/mysql
    environment:
      MARIADB_HOST: paperless
      MARIADB_DATABASE: paperless
      MARIADB_USER: paperless
      MARIADB_PASSWORD: paperless
      MARIADB_ROOT_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ngx_server
    restart: unless-stopped
    depends_on:
      - db
      - broker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data/data:/usr/src/paperless/data
      - ./data/media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: .env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: db
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: paperless
      PAPERLESS_DBPORT: 3306
    security_opt:
      - no-new-privileges:true
    ports:
      - 8001:8000
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperless-ngx.entrypoints=http"
      - "traefik.http.routers.paperless-ngx.rule=Host(`paperless-ngx.local.willkimble.net`)"
      - "traefik.http.middlewares.paperless-ngx-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.paperless-ngx.middlewares=paperless-ngx-https-redirect"
      - "traefik.http.routers.paperless-ngx-secure.entrypoints=https"
      - "traefik.http.routers.paperless-ngx-secure.rule=Host(`paperless-ngx.local.willkimble.net`)"
      - "traefik.http.routers.paperless-ngx-secure.tls=true"
      - "traefik.http.routers.paperless-ngx-secure.service=paperless-ngx"
      - "traefik.http.services.paperless-ngx.loadbalancer.server.port=8000"
      - "traefik.docker.network=proxy"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.paperless-ngx-secure.middlewares=authelia@docker"

networks:
  default:
  proxy:
    external: true

volumes:
  dbdata:
  redisdata:
